services:
  - type: web
    name: telegram-indexing-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: KEY_PATH
        value: key.json
